/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programs;

/**
 *
 * @author ToyBoX
 */
public class Arm_Strong extends javax.swing.JFrame {

    /**
     * Creates new form Arm_Strong
     */
    public Arm_Strong() {
        super("Arm Strong No");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Value = new javax.swing.JTextField();
        asn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Arm Strong Number");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 10, 250, 60);

        Result.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Result);
        Result.setBounds(30, 240, 340, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("---------------------------------------------------------------");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 220, 360, 10);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 230, 320, 60);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enter No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 90, 80, 50);

        Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueActionPerformed(evt);
            }
        });
        jPanel1.add(Value);
        Value.setBounds(120, 90, 260, 50);

        asn.setBackground(new java.awt.Color(255, 0, 0));
        asn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        asn.setForeground(new java.awt.Color(255, 255, 255));
        asn.setText("Check");
        asn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asnActionPerformed(evt);
            }
        });
        jPanel1.add(asn);
        asn.setBounds(20, 163, 360, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 400, 320);

        setSize(new java.awt.Dimension(475, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValueActionPerformed

    private void asnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asnActionPerformed
        String s=Value.getText();
        try{
            int a=Integer.parseInt(s);
            int n=a,b=0,c=0,e=0;
        while(n!=0){
            b=b+1;
            n=n/10;
        }
        n=a;
        while(n!=0){
            e=n%10;
            c+=Math.pow(e,b);
            n=n/10;
        }
       if(c==a) Result.setText(a+" is a Arm Strong Number");
        else Result.setText(a+" is not a Arm Strong Number");
        }
        catch(Exception e){
        Result.setText("Invalid Input");
        }
    }//GEN-LAST:event_asnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arm_Strong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arm_Strong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arm_Strong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arm_Strong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arm_Strong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Result;
    private javax.swing.JTextField Value;
    private javax.swing.JButton asn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
