/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programs;

/**
 *
 * @author ToyBoX
 */
public class Fact extends javax.swing.JFrame {

    /**
     * Creates new form Fact
     */
    public Fact() {
        super("Factorial");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        factno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Find = new javax.swing.JButton();
        Result = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Factorial");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 50, 140, 50);

        factno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factnoActionPerformed(evt);
            }
        });
        jPanel1.add(factno);
        factno.setBounds(170, 110, 140, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Enter No.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 110, 70, 40);

        Find.setBackground(new java.awt.Color(0, 153, 255));
        Find.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Find.setText("Find");
        Find.setToolTipText("");
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });
        jPanel1.add(Find);
        Find.setBounds(130, 180, 90, 30);

        Result.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Result);
        Result.setBounds(60, 220, 260, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 20, 380, 330);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programs/Java.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 670, 370);

        setSize(new java.awt.Dimension(700, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        String s=factno.getText();
        int a=Integer.parseInt(s);
        int f=1;
        for(int i=1;i<=a;i++){
            f=f*i;
            Result.setText("Result :- "+f);
        }
    }//GEN-LAST:event_FindActionPerformed

    private void factnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Find;
    private javax.swing.JLabel Result;
    private javax.swing.JTextField factno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
