/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programs;

/**
 *
 * @author ToyBoX
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        super("Home");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fibonacci = new javax.swing.JButton();
        armstrong = new javax.swing.JButton();
        calculator = new javax.swing.JButton();
        btnFact = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        Fibonacci.setBackground(new java.awt.Color(0, 0, 0));
        Fibonacci.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Fibonacci.setForeground(new java.awt.Color(255, 255, 255));
        Fibonacci.setText("Fibonacci");
        Fibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FibonacciActionPerformed(evt);
            }
        });
        getContentPane().add(Fibonacci);
        Fibonacci.setBounds(160, 160, 100, 23);

        armstrong.setBackground(new java.awt.Color(0, 0, 0));
        armstrong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        armstrong.setForeground(new java.awt.Color(255, 255, 255));
        armstrong.setText("Arm Strong");
        armstrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armstrongActionPerformed(evt);
            }
        });
        getContentPane().add(armstrong);
        armstrong.setBounds(160, 130, 100, 23);

        calculator.setBackground(new java.awt.Color(0, 0, 0));
        calculator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calculator.setForeground(new java.awt.Color(255, 255, 255));
        calculator.setText("Calculator");
        calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorActionPerformed(evt);
            }
        });
        getContentPane().add(calculator);
        calculator.setBounds(160, 190, 100, 23);

        btnFact.setBackground(new java.awt.Color(0, 0, 0));
        btnFact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFact.setForeground(new java.awt.Color(255, 255, 255));
        btnFact.setText("Factorial");
        btnFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactActionPerformed(evt);
            }
        });
        getContentPane().add(btnFact);
        btnFact.setBounds(160, 100, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programs/Image2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 410, 300);

        setSize(new java.awt.Dimension(448, 361));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FibonacciActionPerformed
        new FibonacciNo().setVisible(true);
    }//GEN-LAST:event_FibonacciActionPerformed

    private void armstrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armstrongActionPerformed
        new Arm_Strong().setVisible(true);
    }//GEN-LAST:event_armstrongActionPerformed

    private void btnFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactActionPerformed
        new Fact().setVisible(true);
    }//GEN-LAST:event_btnFactActionPerformed

    private void calculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorActionPerformed
        new Calculator().setVisible(true);
    }//GEN-LAST:event_calculatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fibonacci;
    private javax.swing.JButton armstrong;
    private javax.swing.JButton btnFact;
    private javax.swing.JButton calculator;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}