/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programs;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ToyBoX
 */
public class PalindromeNo extends javax.swing.JFrame {

    /**
     * Creates new form NaturalNo_Sum
     */
    public PalindromeNo() {
        super("Palindrome");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        no = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        Check = new javax.swing.JButton();
        yes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        no.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(no);
        no.setBounds(10, 60, 110, 210);

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Palindrome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 340, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter No.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 70, 100, 40);

        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        jPanel1.add(num);
        num.setBounds(140, 120, 80, 40);

        Check.setBackground(new java.awt.Color(255, 0, 51));
        Check.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Check.setText("Check");
        Check.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });
        jPanel1.add(Check);
        Check.setBounds(135, 180, 90, 60);

        yes.setBackground(new java.awt.Color(102, 255, 0));
        jPanel1.add(yes);
        yes.setBounds(240, 60, 110, 210);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 360, 280);

        setSize(new java.awt.Dimension(414, 346));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numActionPerformed

    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
        String s=num.getText();
        int a=Integer.parseInt(s);
        int b,c=0,n=a;
        while(n!=0){
        b=n%10;
        c=c*10+b;
        n=n/10;
        }
        if(c==a){
            yes.setBackground(Color.green);
            yes.setText(a+" is Palindrome");
            JOptionPane.showMessageDialog(this,a+" is Palindrome" );
            
        }
        else{
            no.setBackground(Color.red);
            no.setText(a+"is not Palindrome");
        JOptionPane.showMessageDialog(this,"Not palin", "Integer", 2);
        }
    }//GEN-LAST:event_CheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PalindromeNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PalindromeNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PalindromeNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PalindromeNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PalindromeNo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel no;
    private javax.swing.JTextField num;
    private javax.swing.JLabel yes;
    // End of variables declaration//GEN-END:variables
}
