/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programs;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.Random;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import short_cut.Connect;

/**
 *
 * @author ToyBoX
 */
public class Student_Marks extends javax.swing.JFrame {

    /**
     * Creates new form Student_Marks
     */
    public Student_Marks() {
        initComponents();
        binddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnames = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmark = new javax.swing.JTextField();
        jbsubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtmarks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mark List");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(27, 20, 390, 32);
        jPanel1.add(txtnames);
        txtnames.setBounds(190, 100, 190, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(57, 100, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mark");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 160, 100, 30);

        txtmark.setEditable(false);
        jPanel1.add(txtmark);
        txtmark.setBounds(190, 160, 190, 30);

        jbsubmit.setBackground(new java.awt.Color(0, 204, 204));
        jbsubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbsubmit.setText("Submit");
        jbsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jbsubmit);
        jbsubmit.setBounds(130, 230, 170, 40);

        jtmarks.setBackground(new java.awt.Color(0, 153, 153));
        jtmarks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtmarks);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(420, 30, 240, 210);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 690, 300);

        setSize(new java.awt.Dimension(739, 373));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void binddata(){
    
        try {
            Connect C=new Connect();
            Connection con=C.getConnection();
            PreparedStatement ps=con.prepareCall("select * from student_marks");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tmod=buildTableModel(rs);
            jtmarks.setModel(tmod);
            while(rs.next()){
                int s=rs.getInt("mark");
                String mark=Integer.toString(s);
                txtmark.setText(mark);
            txtnames.setText(rs.getString("name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }  
    }
        public static DefaultTableModel buildTableModel(ResultSet rs)
            throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();
        Vector colname=new Vector();
        int columnCount=metaData.getColumnCount();
        for (int column=1;column<=columnCount;column++) {
            colname.add(metaData.getColumnName(column));
        }
        Vector data=new Vector();
        while (rs.next()) {
            Vector vector=new Vector();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data,colname);
    }
    private void jbsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsubmitActionPerformed
        String name=txtnames.getText();
        Random R=new Random();
        int m=R.nextInt(100);
        String mark=Integer.toString(m);
        txtmark.setText(mark);
        try {
            Connect C=new Connect();
            Connection con=C.getConnection();
            CallableStatement st=con.prepareCall("{call marks(?,?)}");
            st.setString(1,name);
            int mark1=Integer.parseInt(mark);
            st.setInt(2,mark1);
            st.execute();
            System.out.println("SUCCESS");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbsubmitActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Marks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbsubmit;
    private javax.swing.JTable jtmarks;
    private javax.swing.JTextField txtmark;
    private javax.swing.JTextField txtnames;
    // End of variables declaration//GEN-END:variables
