/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programs;

import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author ToyBoX
 */
public class Timer_Random extends javax.swing.JFrame {

    public Timer_Random() {
        initComponents();
        ran();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtin = new javax.swing.JTextField();
        txtfix = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbluck = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Random & Timer");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 320, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("------------------------------------------------------------------");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 380, 16);
        jPanel1.add(txtin);
        txtin.setBounds(250, 100, 100, 30);

        txtfix.setEditable(false);
        jPanel1.add(txtfix);
        txtfix.setBounds(30, 100, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("=");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 100, 50, 30);

        jbluck.setBackground(new java.awt.Color(255, 0, 102));
        jbluck.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbluck.setText("Luck");
        jbluck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbluckActionPerformed(evt);
            }
        });
        jPanel1.add(jbluck);
        jbluck.setBounds(80, 160, 240, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 60, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 400, 260);

        setSize(new java.awt.Dimension(434, 320));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void rando(){
    Random R=new Random();
    int ro=R.nextInt(100);
    txtfix.setText(""+ro);
    }
    public void ran(){
        Timer t=new Timer();
        TimerTask task=new TimerTask(){
            @Override
            public void run() {
                rando();
            }
        };
        t.scheduleAtFixedRate(task,0,500);
    }
    private void jbluckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbluckActionPerformed
        
        String s1=txtin.getText();
        int a=Integer.parseInt(s1);
        String s2=txtfix.getText();
        int b=Integer.parseInt(s2);
        if(a==b){
                JOptionPane.showMessageDialog(this,"Congratulations you WON");
        }
        else{
        JOptionPane.showMessageDialog(this,"Better luck next time","Bad Luck",2);
        }
    }//GEN-LAST:event_jbluckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timer_Random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timer_Random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timer_Random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timer_Random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timer_Random().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbluck;
    private javax.swing.JTextField txtfix;
    private javax.swing.JTextField txtin;
    // End of variables declaration//GEN-END:variables
}
