/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User_Registration;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import short_cut.Connect;

/**
 *
 * @author ToyBoX
 */
public class Admin1 extends javax.swing.JFrame {

    /**
     * Creates new form Admin1
     */
    public Admin1() {
        initComponents();
        bindComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        register = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jcbid = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrator");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 10, 540, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 230, 70, 30);

        txtid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtid);
        txtid.setBounds(220, 230, 210, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 280, 70, 30);

        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtname);
        txtname.setBounds(220, 280, 210, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Phone No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 330, 80, 30);

        txtphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtphone);
        txtphone.setBounds(220, 330, 210, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("E-mail id");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 380, 70, 30);

        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtemail);
        txtemail.setBounds(220, 380, 210, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 430, 80, 30);

        txtpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtpassword);
        txtpassword.setBounds(220, 430, 210, 30);

        delete.setBackground(new java.awt.Color(0, 204, 255));
        delete.setText("Delete");
        delete.setBorder(null);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(470, 390, 130, 40);

        register.setBackground(new java.awt.Color(0, 204, 255));
        register.setText("Register");
        register.setBorder(null);
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register);
        register.setBounds(470, 250, 130, 40);

        update.setBackground(new java.awt.Color(0, 204, 255));
        update.setText("Update");
        update.setBorder(null);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(470, 320, 130, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("--------------------------------------------------------------");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 60, 600, 30);

        jcbid.setBorder(null);
        jcbid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbidActionPerformed(evt);
            }
        });
        jPanel1.add(jcbid);
        jcbid.setBounds(250, 130, 150, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 650, 580);

        setSize(new java.awt.Dimension(693, 645));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        public void bindComboBox(){
        List<String> data=new ArrayList();
        try{
    Connect C=new Connect();
    Connection con=C.getConnection();
    PreparedStatement ps=con.prepareStatement("select user_id from user_register");
    ResultSet rs=ps.executeQuery();
    while(rs.next()){
    int id1=rs.getInt("user_id");
    data.add(""+id1);
    }
    rs.close();
    jcbid.setModel(new DefaultComboBoxModel<>(data.toArray(new String[0])));
    int id2=rs.getInt("user_id");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
        
        public void addToDatabase(){
                String s=txtid.getText();
		int user_id=Integer.parseInt(s);
		String name=txtname.getText();
		String s1=txtphone.getText();
                long phone=Long.parseLong(s1);
		String email=txtemail.getText();
		String password=txtpassword.getText();
		try {
			Connect C=new Connect();
			Connection con=C.getConnection();
			PreparedStatement ps1=con.prepareStatement("select * from user_register");
			ResultSet rs=ps1.executeQuery();
			while(rs.next()) {
				int user_id1=rs.getInt("user_id");
				long phone1=rs.getLong("phone");
				String email1=rs.getString("email");
				if(user_id1==user_id) {
					JOptionPane.showMessageDialog(this,"User Id Already registered");
                                        txtid.setText("");
					return;
					}
				if(phone1==phone) {
					JOptionPane.showMessageDialog(this,"Phone number Already registered");
                                        txtphone.setText("");
					return;
					}
				if(email1.equals(email)) {
					JOptionPane.showMessageDialog(this,"E-mail Id Already registered");
                                        txtemail.setText("");
					return;
					}
				}
			PreparedStatement ps2=con.prepareStatement("Insert into user_register values(?,?,?,?,?)");
			ps2.setInt(1,user_id);
			ps2.setString(2,name);
			ps2.setLong(3,phone);
			ps2.setString(4,email);
			ps2.setString(5,password);
			int i=ps2.executeUpdate();
			if(i>0){
				JOptionPane.showMessageDialog(this,"Registration Successful");
                                txtid.setText("");
                                txtname.setText("");
                                txtphone.setText("");
                                txtemail.setText("");
                                txtpassword.setText("");
				}
			else {
				JOptionPane.showMessageDialog(this,"Registration Failed","Failed",2);
				}
			}
		catch (Exception e) {
			e.printStackTrace();
		}
    }
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try{
            String s=txtid.getText();
            int id=Integer.parseInt(s);
            Connect C=new Connect();
            Connection con=C.getConnection();
            PreparedStatement ps=con.prepareStatement("Delete from user_register where User_ID=?");
            ps.setInt(1,id);
            int count=ps.executeUpdate();
            if(count>0) {
                JOptionPane.showMessageDialog(this,"Deletion Success");
                txtid.setText("");
                txtname.setText("");
                txtphone.setText("");
                txtemail.setText("");
                txtpassword.setText("");
            }
            else {
                JOptionPane.showMessageDialog(this,"Deletion Failed");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        bindComboBox();
    }//GEN-LAST:event_deleteActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        addToDatabase();
        bindComboBox();
    }//GEN-LAST:event_registerActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        try{
            String id=txtid.getText();
            int user_id=Integer.parseInt(id);
            String name=txtname.getText();
            String pho=txtphone.getText();
            long phone=Long.parseLong(pho);
            String email=txtemail.getText();
            String password=txtpassword.getText();
            Connect C=new Connect();
            Connection con=C.getConnection();
            PreparedStatement ps=con.prepareStatement("Update user_register set user_id=?, name=?, phone=?, email=?, password=? where user_id=?");
            ps.setInt(1,user_id);
            ps.setString(2,name);
            ps.setLong(3,phone);
            ps.setString(4,email);
            ps.setString(5,password);
            ps.setString(6,id);
            ps.executeUpdate();
            int count=ps.executeUpdate();
            if(count>0) {
                JOptionPane.showMessageDialog(this,"Updation Success");
                txtid.setText("");
                txtname.setText("");
                txtphone.setText("");
                txtemail.setText("");
                txtpassword.setText("");
            }
            else {
                JOptionPane.showMessageDialog(this,"Updation Failed");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateActionPerformed

    private void jcbidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbidActionPerformed
        String select=(String) jcbid.getSelectedItem();
        int id=Integer.parseInt(select);
        try{
            Connect C=new Connect();
            Connection con=C.getConnection();
        PreparedStatement ps=con.prepareStatement("select * from user_register where user_id=?");
        ps.setInt(1,id);
        ResultSet rs=ps.executeQuery();
        while(rs.next()){
            txtid.setText(rs.getString("user_id"));
            txtname.setText(rs.getString("name"));
            txtphone.setText(rs.getString("phone"));
            txtemail.setText(rs.getString("email"));
            txtpassword.setText(rs.getString("password"));
        }
        }
        catch(Exception e){
        e.printStackTrace();
        }
    }//GEN-LAST:event_jcbidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbid;
    private javax.swing.JButton register;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphone;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
