/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User_Registration;

import java.util.ArrayList;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.dynalink.StandardNamespace;
import short_cut.*;
public class Search_ComboBox extends javax.swing.JFrame {

    /**
     * Creates new form Search_ComboBox
     */
    public Search_ComboBox() {
        initComponents();
        bindComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbname = new javax.swing.JComboBox<>();
        details = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jPanel1.add(jcbname);
        jcbname.setBounds(40, 70, 120, 30);

        details.setBackground(new java.awt.Color(0, 153, 255));
        details.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        details.setText("Details");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });
        jPanel1.add(details);
        details.setBounds(200, 70, 160, 30);

        info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name", "Phone", "E-mail", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(info);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 452, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 470, 220);

        setSize(new java.awt.Dimension(543, 285));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void bindComboBox(){
    List<String> names=new ArrayList();
    try{
    Connect C=new Connect();
    Connection con=C.getConnection();
    PreparedStatement ps=con.prepareStatement("select name from user_register");
    ResultSet rs=ps.executeQuery();
    while(rs.next()){
    String name1=rs.getString("name");
    names.add(""+name1);
    }
    rs.close();
    jcbname.setModel(new DefaultComboBoxModel<>(names.toArray(new String[0])));
    }
    catch(Exception e){
    e.printStackTrace();
    }
}

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed

        String name1=jcbname.getSelectedItem().toString();
		try {
			Connect C=new Connect();
			Connection con=C.getConnection();
			PreparedStatement ps=con.prepareStatement("select * from user_register");
			ResultSet rs=ps.executeQuery();
			while(rs.next()) {
				String name2=rs.getString("name");
				if(name2.equals(name1)) {
					int user_id=rs.getInt("user_id");
					String name=rs.getString("name");
					long phone=rs.getLong("phone");
					String email=rs.getString("email");
					String password=rs.getString("password");
					String id=Integer.toString(user_id);
                                        String pho=Long.toString(phone);
                                        String data[]={id,name,pho,email,password};
                                        DefaultTableModel table=(DefaultTableModel)info.getModel();
                                        table.addRow(data);
					}
				}
			}
		catch (Exception e) {
			e.printStackTrace();
		}
    }//GEN-LAST:event_detailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_ComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton details;
    private javax.swing.JTable info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbname;
    // End of variables declaration//GEN-END:variables
}
