/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User_Registration;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import short_cut.*;

public class Search extends javax.swing.JFrame {

    public Search() {
        super("Search");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jbnsearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 50, 70, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Phone No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 50, 80, 30);

        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtname);
        txtname.setBounds(90, 50, 180, 30);

        txtphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtphone);
        txtphone.setBounds(390, 50, 200, 30);

        jbnsearch.setBackground(new java.awt.Color(0, 204, 255));
        jbnsearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbnsearch.setText("Search");
        jbnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(jbnsearch);
        jbnsearch.setBounds(240, 120, 130, 40);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(null);

        info.setBackground(new java.awt.Color(204, 204, 204));
        info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(info);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(12, 20, 560, 190);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 190, 580, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 20, 620, 440);

        setSize(new java.awt.Dimension(708, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void time(){
    
    }
    public void searchValues(){
                boolean found=false;
		String name1=txtname.getText();
                String phone1=txtphone.getText();
		name1=name1.toLowerCase();
		try {
			Connect C=new Connect();
			Connection con=C.getConnection();
			PreparedStatement ps=con.prepareStatement("select * from user_register where name like ?");
			ps.setString(1,"%"+name1+"%");
			ResultSet rs=ps.executeQuery();
			while(rs.next()) {
                            String name2=rs.getString("name");
                            name2=name2.toLowerCase();
                            if(name2.contains(name1)){
                            DefaultTableModel tm=buildTableModel(rs);
                        info.setModel(tm);
                        found=true;
                            }
				}
			if(!found)JOptionPane.showMessageDialog(this,"---------- Name does not exist ----------");
                        return;
			}
		catch (Exception e) {
			e.printStackTrace();
		}
                try {
			Connect C=new Connect();
			Connection con=C.getConnection();
			PreparedStatement ps=con.prepareStatement("select * from user_register where phone like ?");
			ps.setString(1,"%"+phone1+"%");
			ResultSet rs=ps.executeQuery();
			while(rs.next()) {
				long pho=rs.getLong("phone");
                                String phone2=Long.toString(pho);
				if(phone2.contains(phone1)||phone2.equals(phone1)) {
					DefaultTableModel tm=buildTableModel(rs);
                                        info.setModel(tm);
					found=true;
					}
				}
			if(!found)JOptionPane.showMessageDialog(this,"---------- Phone number does not exist ----------");
                        return;
			}
		catch (Exception e) {
			e.printStackTrace();
		}
    }
    public static DefaultTableModel buildTableModel(ResultSet rs)
                 throws SQLException{
        ResultSetMetaData metaData=rs.getMetaData();
        Vector Cname=new Vector();
        int Ccount=metaData.getColumnCount();
        for(int i=1;i<=Ccount;i++){
        Cname.add(metaData.getColumnName(i));
        }
        Vector data=new Vector();
        while (rs.next()) {            
            Vector v=new Vector();
            for(int j=1;j<=Ccount;j++){
            v.add(rs.getObject(j));
            }
            data.add(v);
        }
        return new DefaultTableModel(data,Cname);
    }
    private void jbnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnsearchActionPerformed

        searchValues();
    }//GEN-LAST:event_jbnsearchActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable info;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnsearch;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
