/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package numbers;

/**
 *
 * @author ToyBoX
 */
public class num extends javax.swing.JFrame {

    /**
     * Creates new form num
     */
    public num() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OP = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        OP1 = new javax.swing.JLabel();
        OP2 = new javax.swing.JLabel();
        OP3 = new javax.swing.JLabel();
        OP4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        OP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(OP);
        OP.setBounds(130, 220, 70, 60);

        jButton1.setText("Count");
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 180, 72, 23);

        jButton2.setText("Avg");
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 180, 72, 23);

        jButton3.setText("Sum");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(310, 180, 72, 23);

        jButton4.setText("Min");
        jPanel1.add(jButton4);
        jButton4.setBounds(30, 180, 72, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 0, 452, 160);

        OP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(OP1);
        OP1.setBounds(220, 220, 70, 60);

        OP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(OP2);
        OP2.setBounds(310, 220, 70, 60);

        OP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(OP3);
        OP3.setBounds(400, 220, 70, 60);

        OP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(OP4);
        OP4.setBounds(30, 220, 70, 60);

        jButton5.setText("Max");
        jPanel1.add(jButton5);
        jButton5.setBounds(130, 180, 72, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 490, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(num.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(num.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(num.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(num.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new num().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OP;
    private javax.swing.JLabel OP1;
    private javax.swing.JLabel OP2;
    private javax.swing.JLabel OP3;
    private javax.swing.JLabel OP4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
